### ISSUE TITLE
Several issues identified

### ISSUE THREAD

**Issue by tthtlc** [yang-lile/flutter_assistant#1]
Your repository have several bugs today.   

After applying the following patch today (flutter 3.3.7, kotlin version: 1.7.21) I got successful compilation of your repository:

https://gist.github.com/tthtlc/25f3318ff51d4c880c934d8ca49114d9

**Comment by yang-lile** [comment]
got it, I will fix them soon, thanks

**Comment by yang-lile** [comment]
It's been fixed, is it okey with you? @tthtlc
